'use client'

import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import { FileText } from 'lucide-react'

interface Props {
    analysis: any
    logFile: any
}

export default function AnalysisReport({ analysis, logFile }: Props) {
    const generatePDF = () => {
        const doc = new jsPDF()

        // Title
        doc.setFontSize(20)
        doc.text('LogIz Security Analysis Report', 14, 22)

        // Metadata
        doc.setFontSize(10)
        doc.text(`File Name: ${logFile.originalName}`, 14, 32)
        doc.text(`Analysis ID: ${analysis.id}`, 14, 38)
        doc.text(`Date: ${new Date(analysis.analyzedAt).toLocaleString()}`, 14, 44)

        // Summary Stats
        doc.setFontSize(14)
        doc.text('Summary', 14, 55)

        const stats = [
            ['Total Threats', analysis.threatCount],
            ['Critical', analysis.threats.filter((t: any) => t.severity === 'CRITICAL').length],
            ['High', analysis.threats.filter((t: any) => t.severity === 'HIGH').length],
            ['Medium', analysis.threats.filter((t: any) => t.severity === 'MEDIUM').length],
            ['Low', analysis.threats.filter((t: any) => t.severity === 'LOW').length],
        ]

        autoTable(doc, {
            startY: 60,
            head: [['Metric', 'Count']],
            body: stats,
            theme: 'striped',
            headStyles: { fillColor: [0, 240, 255] }, // Cyber Blue
        })

        // Threat Details
        doc.setFontSize(14)
        // @ts-ignore
        doc.text('Detailed Threat Analysis', 14, doc.lastAutoTable.finalY + 15)

        const threats = analysis.threats.map((t: any) => [
            t.severity,
            t.type,
            t.description,
            t.sourceIP || 'N/A',
            t.confidence ? `${(t.confidence * 100).toFixed(0)}%` : 'N/A'
        ])

        autoTable(doc, {
            // @ts-ignore
            startY: doc.lastAutoTable.finalY + 20,
            head: [['Severity', 'Type', 'Description', 'Source IP', 'Confidence']],
            body: threats,
            theme: 'grid',
            styles: { fontSize: 8 },
            columnStyles: {
                0: { fontStyle: 'bold' }, // Severity
                2: { cellWidth: 60 } // Description
            },
            didParseCell: (data) => {
                if (data.section === 'body' && data.column.index === 0) {
                    const severity = data.cell.raw
                    if (severity === 'CRITICAL') data.cell.styles.textColor = [255, 0, 60] // Red
                    if (severity === 'HIGH') data.cell.styles.textColor = [255, 87, 51] // Orange
                }
            }
        })

        // Footer
        const pageCount = doc.getNumberOfPages()
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i)
            doc.setFontSize(8)
            doc.text(
                `Generated by LogIz AI - Page ${i} of ${pageCount}`,
                doc.internal.pageSize.width / 2,
                doc.internal.pageSize.height - 10,
                { align: 'center' }
            )
        }

        doc.save(`logiz-report-${logFile.originalName}.pdf`)
    }

    return (
        <button
            onClick={(e) => {
                e.stopPropagation()
                generatePDF()
            }}
            className="flex items-center space-x-2 px-3 py-1.5 rounded-lg bg-gray-800 hover:bg-gray-700 text-sm text-gray-300 transition-colors border border-gray-700"
        >
            <FileText className="w-4 h-4" />
            <span>Download Report</span>
        </button>
    )
}
