var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/upload/route.js")
R.c("server/chunks/[root-of-the-server]__a5d2e6ca._.js")
R.c("server/chunks/node_modules_next_f639fd26._.js")
R.c("server/chunks/node_modules_next-auth_1810886e._.js")
R.c("server/chunks/node_modules_openid-client_d15f72b3._.js")
R.c("server/chunks/node_modules_jose_dist_node_cjs_bd88468e._.js")
R.c("server/chunks/node_modules_@supabase_realtime-js_dist_module_306ac729._.js")
R.c("server/chunks/node_modules_@supabase_storage-js_dist_module_473cf4b8._.js")
R.c("server/chunks/node_modules_@supabase_auth-js_dist_module_d4605ced._.js")
R.c("server/chunks/node_modules_0123c182._.js")
R.c("server/chunks/[root-of-the-server]__bacab3f1._.js")
R.c("server/chunks/_next-internal_server_app_api_upload_route_actions_f15ed185.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/upload/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/upload/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
